### ISSUE TITLE
Github URL update

### ISSUE THREAD

**Issue by Gamecock** [iannerney/skywaybridgestatus#3]
Github URL is fixed in master, but branch feature-status-notifier is deployed..  Need to update URL on that branch.

**Comment by Gamecock** [comment]
You OK with me taking this on.  Never done any PHP, and can't start for a few weeks, so it might be a while.  New to the area and just bought a house in Manatee so I have some interest in this project.

**Comment by iannerney** [comment]
That's great, thanks for doing that! I moved the repo a few months back and forgot to update that reference. I'll be sure to merge in `master` before committing that feature.

I'm working on the notification feature now, I'm hoping to have it pushed shortly to let everyone know when it opens.

**Comment by iannerney** [comment]
@Gamecock - When you commit your change to master, could you please submit a pull request? I'll get that merged in today.

**Comment by iannerney** [comment]
This is now fixed on production, closing as complete. :)
